// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQt2IRhk-GzReQSXuz85DRMV7LHYCYNwE',
    appId: '1:271315539363:web:0f360eac1ef1e771527616',
    messagingSenderId: '271315539363',
    projectId: 'quran-chat-ae0c1',
    authDomain: 'quran-chat-ae0c1.firebaseapp.com',
    storageBucket: 'quran-chat-ae0c1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvSJGcZgwcoIZ5z7gEhppotKH5DapjkZc',
    appId: '1:271315539363:android:baa0ff3681a54839527616',
    messagingSenderId: '271315539363',
    projectId: 'quran-chat-ae0c1',
    storageBucket: 'quran-chat-ae0c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDi9zl9ufX8zKUl4IO5mlk7iY6bbYJMdg',
    appId: '1:271315539363:ios:6716e0929b55e09b527616',
    messagingSenderId: '271315539363',
    projectId: 'quran-chat-ae0c1',
    storageBucket: 'quran-chat-ae0c1.firebasestorage.app',
    iosBundleId: 'com.app.quranchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDi9zl9ufX8zKUl4IO5mlk7iY6bbYJMdg',
    appId: '1:271315539363:ios:45070cdf8760f663527616',
    messagingSenderId: '271315539363',
    projectId: 'quran-chat-ae0c1',
    storageBucket: 'quran-chat-ae0c1.firebasestorage.app',
    iosBundleId: 'com.example.qurani22',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQt2IRhk-GzReQSXuz85DRMV7LHYCYNwE',
    appId: '1:271315539363:web:b25344cbd9879be1527616',
    messagingSenderId: '271315539363',
    projectId: 'quran-chat-ae0c1',
    authDomain: 'quran-chat-ae0c1.firebaseapp.com',
    storageBucket: 'quran-chat-ae0c1.firebasestorage.app',
  );

}